spring.application.name=learning-platform-backend

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# POSTGRES DATABASE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT
# ===============================
jwt.secret=57483d61ff41d08e0f79411eb022fd106068e70f287d99eca9cefd4c872e3a39
jwt.expiration=86400000
