spring.application.name=learning-platform-backend

# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE CONFIG (Railway)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT (correct dialect for Spring Boot 3)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# CONNECTION STABILITY (VERY IMPORTANT ON CLOUD)
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=57483d61ff41d08e0f79411eb022fd106068e70f287d99eca9cefd4c872e3a39
jwt.expiration=86400000
